var

POKMSK : byte absolute $10;
RTCLOK : byte absolute $14;
ATRACT : byte absolute $4D;
COLCRS : byte absolute $55;
SAVMSC : word absolute $58;
OLDCHR : byte absolute $5D;
VDSLST : word absolute $200;
SDMCTL : byte absolute $22F;
SDLSTL : word absolute $230;
COLOR0 : byte absolute $2C4;
COLOR1 : byte absolute $2C5;
COLOR2 : byte absolute $2C6;
COLOR3 : byte absolute $2C7;
COLOR4 : byte absolute $2C8;
HELPFG : byte absolute $2DC;
CHBAS  : byte absolute $2F4;
CH     : byte absolute $2FC;

IRQEN  : byte absolute $D20E;
PORTB  : byte absolute $D301;
VCOUNT : byte absolute $D40B;
NMIEN  : byte absolute $D40E;


//RANDOM : byte absolute $D20A;
//KBCODE : byte absolute $D209;